#!/bin/bash

# =================================
# FARGO3D: DRIFT - CLI ORCHESTRATOR
# =================================

# Stop the script on an unexpected error.
set -e

# Local Python path.
PYTHON_BIN='./.venv/bin/python'

# Principal commands.
COMMAND=$1
OPTION=$2

# Colors.
ERROR='\033[0;31m'   # Red.
INFO='\033[0;33m'    # Yellow.
TITLE='\033[0;34m'   # Blue.
SUCCESS='\033[0;36m' # Cyan.
NC='\033[0m'         # No Color.

# Case: Virtual enviroment not found.
if [ ! -f "$PYTHON_BIN" ]; then
    echo    ''
    echo -e "${ERROR}[CRITICAL ERROR]${NC} Virtual environment not found at ./.venv/"
    echo    'Please ensure the .venv directory exists at the root of this software.'
    echo    'To create a virtual enviroment you can run the following command on the root directory:'
    echo    ''
    echo -e "${INFO}  python3 -m venv .venv${NC}"
    echo -e "${INFO}  .venv/bin/pip install -r requirements.txt${NC}"
    echo    ''
    exit 1
fi

# Welcome banner
show_welcome() {
    echo ""
    echo -e "${INFO}"
    cat << "EOF"
==============================================================
  * .    .    * .       * .     * .     .  *
     ██████╗ ██████╗ ██╗███████╗████████╗   .     * .
     ██╔══██╗██╔══██╗██║██╔════╝╚══██╔══╝      *
     ██║  ██║██████╔╝██║█████╗     ██║        .    .  *
     ██║  ██║██╔══██╗██║██╔══╝     ██║       *
     ██████╔╝██║  ██║██║██║        ██║     .     * .
     ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝        ╚═╝            .
--------------------------------------------------------------
  DYNAMIC RUNTIME INFRASTRUCTURE FOR FARGO3D TRACKING
==============================================================
EOF
    echo -e "${NC}"
    echo -e "Version 1.0.0 | Built for FARGO3D Multiple Simulations"
    echo    ""
    echo -e "ENVIRONMENT CONFIGURATION"
    echo    ""
    echo -e "Before deploying simulations, ensure your root paths are set up in:"
    echo    ''
    echo -e "    ${INFO}utils/drift_config.json${NC}"
    echo    ''
    echo -e "USAGE"
    echo    ''
    echo -e "    ${INFO}./drift [command] [options]${NC}"
    echo    ''
    echo -e "AVAILABLE MODULES & COMMANDS"
    echo    ""
    echo -e "    ${INFO}forge${NC}                Deployment & matrix generation engine."
    echo -e "        ${INFO}-b, --blueprint${NC}      Scan setups and generate the parameter blueprint (.json)."
    echo -e "        ${INFO}-d, --deploy${NC}         Build parameter matrix, .par files, and directory tree."
    echo    ''
    echo -e "    ${INFO}void${NC}                 Controlled directory purging engine."
    echo -e "        ${INFO}-a, --all${NC}            Wipe config/, logs/, and outputs/ (Clean reset)."
    echo -e "        ${INFO}-c, --configs${NC}        Wipe and purge all blueprint files in configs/."
    echo -e "        ${INFO}-l, --logs${NC}           Wipe and purge all log files in logs/."
    echo -e "        ${INFO}-o, --outputs${NC}        Wipe and purge all run directories in outputs/."
    echo    ""
    echo -e "    ${INFO}sentinel${NC}             Global telemetry & system state controller."
    echo -e "        ${INFO}-e, --enablelogs${NC}     Enable the log writting on logs/."
    echo -e "        ${INFO}-d, --disablelogs${NC}    Disable the log writting on logs/."
    echo -e "        ${INFO}-s, --status${NC}         Checks the current state of log writting."
    echo    ""
    echo -e "    ${ERROR}launch${NC}              Simulation execution engine ${INFO}[In Development]${NC}."
    echo -e "    ${ERROR}unify${NC}               Data aggregation & post-processing engine ${INFO}[In Development]${NC}."
    echo    ''
    echo -e "Run ${INFO}./drift help${NC} or simply ${INFO}./drift${NC} at any time to show this panel."
    echo    ''
}

case "$COMMAND" in
    ""|help|-h|--help|welcome)
        show_welcome
        exit 0
        ;;
    forge)
        if [[ "$OPTION" == '-b' || "$OPTION" == '--blueprint' ]]; then

            # Executes FORGE module first phase.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}FORGE: PHASE I${NC} engine..."
            $PYTHON_BIN src/FORGE/forge_I.py
            
        elif [[ "$OPTION" == '-d' || "$OPTION" == '--deploy' ]]; then
        
            # Executes FORGE module second phase.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}FORGE: PHASE II${NC} engine..."
            $PYTHON_BIN src/FORGE/forge_II.py

        else
        
            # Case: Unknown options.
            echo    ''
            echo -e "${ERROR}[ERROR]${NC} Unknown option for FORGE module: ${INFO}$OPTION${NC}"
            echo -e 'Available options:'
            echo -e "${INFO}    -b, --blueprint${NC}  Scan setups and generate the parameter blueprint."
            echo -e "${INFO}    -d, --deploy${NC}     Generate the parameter matrix, the .par files and directory tree in outputs/."
            echo    ''
            exit 1

        fi
        ;;

    launch)
        echo -e "${INFO}This module is not yet ready.${NC}"
        ;;
        
    sentinel)
        if [[ "$OPTION" == '-e' || "$OPTION" == '--enablelogs' ]]; then

            # Executes SENTINEL module for enabling log writting.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}SENTINEL${NC} engine..."
            $PYTHON_BIN src/SENTINEL/logs.py --enablelogs
            echo    ''
            
        elif [[ "$OPTION" == '-d' || "$OPTION" == '--disablelogs' ]]; then
        
            # Executes SENTINEL module for disabling log writting.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}SENTINEL${NC} engine..."
            $PYTHON_BIN src/SENTINEL/logs.py --disablelogs
            echo    ''

        elif [[ "$OPTION" == '-s' || "$OPTION" == '--status' ]]; then
        
            # Executes SENTINEL module for checking state of log writting.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}SENTINEL${NC} engine..."
            $PYTHON_BIN src/SENTINEL/logs.py --status
            echo  

        else
        
            # Case: Unknown options.
            echo    ''
            echo -e "${ERROR}[ERROR]${NC} Unknown option for SENTINEL module: ${INFO}$OPTION${NC}"
            echo -e 'Available options:'
            echo -e "        ${INFO}-e, --enablelogs${NC}     Enable the log writting on logs/."
            echo -e "        ${INFO}-d, --disablelogs${NC}    Disable the log writting on logs/."
            echo -e "        ${INFO}-s, --status${NC}         Checks the current state of log writting."
            echo    ''
            exit 1

        fi
        ;;

    unify)
        echo -e "${INFO}This module is not yet ready.${NC}"
        ;;

    void)

        if [[ "$OPTION" == '-a' || "$OPTION" == "--all" ]]; then

            # Executes VOID module to wipe outputs directory content.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}VOID${NC} engine: Purging config, logs and outputs directories..."
            echo    ''
            $PYTHON_BIN src/VOID/void.py --all
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Process ${SUCCESS}VOID${NC} has terminated successfully."
            echo    ''

        elif [[ "$OPTION" == '-c' || "$OPTION" == '--configs' ]]; then

            # Executes VOID module to wipe configs directory content.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}VOID${NC} engine: Purging configs directory..."
            echo    ''
            $PYTHON_BIN src/VOID/void.py --configs
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Process ${SUCCESS}VOID${NC} has terminated successfully."
            echo    ''

        elif [[ "$OPTION" == '-l' || "$OPTION" == "--logs" ]]; then

            # Executes VOID module to wipe logs directory content.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}VOID${NC} engine: Purging logs directory..."
            echo    ''
            $PYTHON_BIN src/VOID/void.py --logs
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Process ${SUCCESS}VOID${NC} has terminated successfully."
            echo    ''

        elif [[ "$OPTION" == '-o' || "$OPTION" == "--outputs" ]]; then

            # Executes VOID module to wipe outputs directory content.
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Launching ${SUCCESS}VOID${NC} engine: Purging outputs directory..."
            echo    ''
            $PYTHON_BIN src/VOID/void.py --outputs
            echo    ''
            echo -e "${TITLE}[DRIFT]${NC} Process ${SUCCESS}VOID${NC} has terminated successfully."
            echo    ''

        else

            # Case: Unknown options for VOID module.
            echo    ''
            echo -e "${ERROR}[ERROR]${NC} Unknown option for VOID module: ${INFO}$OPTION${NC}"
            echo -e 'Available options:'
            echo -e "${INFO}    -a, --all${NC}      Wipe and purge all files in configs/, logs/ and outputs/. This is a clean reset."
            echo -e "${INFO}    -c, --configs${NC}  Wipe and purge all files in configs/."
            echo -e "${INFO}    -l, --logs${NC}     Wipe and purge all files in logs/."
            echo -e "${INFO}    -o, --outputs${NC}  Wipe and purge all files in outputs/."
            echo    ''
            exit 1

        fi
        ;;

    # Case: Unknown command.  
    *)
        echo ""
        echo -e "${ERROR}[ERROR]${NC} Unknown command: '${COMMAND}'"
        echo -e "Run ${INFO}./drift help${NC} to view available modules, options, and setup instructions."
        echo ""
        exit 1
        ;;
esac